services:
  mongodb:
    image: mongo:7.0
    container_name: mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: musicdb
    volumes:
      - mongodb_data:/data/db
      - ./mongo-seed:/docker-entrypoint-initdb.d
    networks:
      - music-network

  api:
    build: ./api
    container_name: music-api
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/musicdb
      - DEBUG=True
    depends_on:
      - mongodb
    networks:
      - music-network
    volumes:
      - ./api:/app

volumes:
  mongodb_data:
    driver: local

networks:
  music-network:
    driver: bridge
